### ISSUE TITLE
(LetThereBeLight bug) goto main menu and goto settings causing crash

### ISSUE THREAD

**Issue by abenkovskii** [malahx/QuickGoTo#1]
I'm not quite sure that crash is the right word: after going from KSC to settings or main menu game window remains open and buttons visually react on mouse-over and clicking but I can't leave main menu / start game scene.

**Comment by malahx** [comment]
I don't have this issue, can you send me your modlist and your logs?

**Comment by abenkovskii** [comment]
== It is a compatibility issue ==
I tested it again on my main install and on "clean" (only QuickGoTo) install.
Can't reproduce this bug on the "clean" install but the main keeps crashing. So it looks like incompatibility. It is not a memory problem (only ~1.5 GB used).
== log ==
log: https://www.dropbox.com/s/k799u5aglufx0eo/output_log.txt?dl=0
== modlist ==
ckan metapackage containing almost all mods I'm using https://www.dropbox.com/s/32yig9wg56r33n5/installed-default.ckan?dl=0
mods not form CKAN:
1) KSPStockTweaks-v1.2
2) QuickGoTo-0.10
3) RemoteTech_XF-1.6.3.1
4) SETI-Greenhouse-0.9.0
5) TweakableWheels
== how to reproduce ==
1) Start new sandbox game.
2) From KSC try GoToMainMenu.
3) Now loading game, starting new game and opening settings should not work.

**Comment by abenkovskii** [comment]
# update
Tested it w/o mods not from CKAN, ActiveTextureManagement and TextureReplacer. Bug still happens.
## log
## modlist

**Comment by abenkovskii** [comment]
##### update
One more test with only part of my mods installed. No bug.
###### modlist
https://www.dropbox.com/s/t0aax9fyq2an8jm/installed-default%20%283%29.ckan?dl=0

**Comment by abenkovskii** [comment]
##### update
Narrowed it down to 25 mods (including QuickGoTo). Bug reproduced on this modlist.
###### modlist
https://www.dropbox.com/s/gdmanautn7emepq/installed-default%20%284%29.ckan?dl=0

**Comment by abenkovskii** [comment]
##### update
Yet another 6 mods that does NOT cause this issue. I'm trying to split modes in a half but all those dependencies are making it harder.
###### modlist
https://www.dropbox.com/s/6yg5juhbloh7oop/installed-default%20%285%29.ckan?dl=0

**Comment by abenkovskii** [comment]
##### update
Yet another 11 mods compatible with QuickGoTo.
###### modlist
https://www.dropbox.com/s/ave9hz4ada9otmg/installed-default%20%286%29.ckan?dl=0

**Comment by abenkovskii** [comment]
##### update
11 mods can reproduce
###### log
https://www.dropbox.com/s/cyw0cok6p0wyf4e/output_log%20%284%29.txt?dl=0
###### modlist
https://www.dropbox.com/s/gs6zm2pw1mh8qek/installed-default%20%287%29.ckan?dl=0

**Comment by abenkovskii** [comment]
##### update
6 mods (including this). Bug is still present.
###### log
https://www.dropbox.com/s/je87l8uuzy21p94/output_log%20%285%29.txt?dl=0
###### modlist
https://www.dropbox.com/s/zzi8ir896scy7l0/installed-default%20%288%29.ckan?dl=0
P.S. I'll delete all those progress updates after I narrow it down to one mod.

**Comment by abenkovskii** [comment]
##### update
It's not MM, RT or toolbar.

**Comment by abenkovskii** [comment]
Yep I found it!
Incompatible mod: LetThereBeLight.
CKAN package: https://www.dropbox.com/s/ib47bekbmikqp0a/incompatible.ckan?dl=0
KSP log: https://www.dropbox.com/s/wovvcfrk4ilcauw/crash_log.txt?dl=0
P.S. now I low CKAN even more.
P.P.S. I'm surprised. I was 99% sure that LetThereBeLight is a very simple plugin that is simple plugin that should not cause any issues.
P.P.P.S. I'll create an issue in LetThereBeLight's repo too.

**Comment by malahx** [comment]
It's a tiny bug with how LetThereBeLight destroy his stock toolbar button ;)
Thanks for the report (I think I can do nothing on it on QuickGoto).

**Comment by tkheikkila** [comment]
Thank you for bringing this to my attention! The bug should be squashed in the latest version.
